Project-Unifest/unifest-android

- core/designsystem/src/main/res/drawable/ic_chevron_left.xml
- core/designsystem/src/main/res/drawable/ic_chevron_right.xml
- core/designsystem/src/main/res/values/colors.xml
- core/designsystem/src/main/res/values/strings.xml
- feature/home/build.gradle.kts
- feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/Utils.kt
- feature/main/src/main/kotlin/com/unifest/android/feature/main/MainActivity.kt
- feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
- gradle/libs.versions.toml
- 홈화면에 앱에서 사용할 Calendar 라이브러리를 연동만 해놨습니다. 
- 달과 요일이 한글로 보이도록 설정해놨습니다. 
- 이제 figma 디자인에 맞게 커스텀하면 될 것 같습니다.
- Main 화면 배경색, BottomBar 색상 흰색으로 고정(다크모드는 아직 계획이 없으므로)
|확장|축소|
|:-----:|:-----:|
|<img width="360" src="https://github.com/Project-Unifest/unifest-android/assets/51016231/9b1c2f3c-f62e-4194-9254-a120b01db51c">|<img width="360" src="https://github.com/Project-Unifest/unifest-android/assets/51016231/6ff90e14-b789-47a2-b15e-2d004ad2c899">|
P.S
참고로 checkout 해서 실행 해보시면 AnimatedVisibility API를 통해 확장 축소때 애니메이션이 자연스럽게 발생합니다.
https://github.com/kizitonwose/Calendar 해당 라이브러리 클론해서 sample 쪽 확인해보면 컴포즈 예제9개있는데 그중 젤 마지막 Example9AnimatedVisibility 코드 참고했습니다. 구현하면서 필요한 기능같은 것들은 sample 들 뒤져보면서 하면 될 것 같아요.
> [feat] [#20] Home 화면 Calendar 라이브러리 연동

- core/designsystem/src/main/res/values/strings.xml
- core/domain/build.gradle.kts
- core/domain/src/main/kotlin/com/unifest/android/core/domain/entity/SchoolEntity.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
- feature/intro/build.gradle.kts
- feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
기존 논의한대로 학교 목록과 관심 목록 지정한 부분을 lazyVerticalGrid 로 교체했습니다.
해당 내용으로 간격조정은 잘 되었지만, 전체 영역은 Column 으로 하기로 한 부분은 lazyVerticalGrid의 height가 지정되지 않는이상 오류가 나더라구요. 그래서 school 개수에 맞게 height값을
.height(
when {
selectedSchools.isEmpty() -> 0.dp
else -> {
val rows = ((selectedSchools.size - 1) / 3 + 1) * 180
rows.dp
}
}
),
로 조정해주었습니다.
또한 Scroll 부분 관련해서, lazyVerticalGrid의 Scroll을 enable false하는 부분이 없는거같은데.. 일단은 그부분은 두고
리소스 추가나 디자인 좀 변경했습니다.
색상 관련부분은 완전히 나오면 제가 수정할게요
> [feat] [#19] Intro 화면 UI

- core/data/build.gradle.kts
- core/data/src/main/kotlin/com/unifest/android/core/data/di/DataSourceModule.kt
- core/data/src/main/kotlin/com/unifest/android/core/data/di/RepositoryModule.kt
- core/data/src/main/kotlin/com/unifest/android/core/data/repository/OnboardingRepository.kt
- core/data/src/main/kotlin/com/unifest/android/core/data/repository/OnboardingRepositoryImpl.kt
- core/datastore/src/main/kotlin/com/unifest/android/core/datastore/MyClass.kt
- core/datastore/src/main/kotlin/com/unifest/android/core/datastore/OnboardingDataSource.kt
- core/datastore/src/main/kotlin/com/unifest/android/core/datastore/OnboardingDataSourceImpl.kt
- core/datastore/src/main/kotlin/com/unifest/android/core/datastore/di/DataStoreModule.kt
- core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/TopAppBar.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
툴팁 관련 설정을 추가하였습니다. checkout 해서 정상적으로 동작하는지 확인부탁드립니다. 
dataStore 관련 설정 초기화는 앱 정보 들어가서 데이터 삭제하면 됩니다.
- 툴팁을 누르거나, MapTopAppBar내에 Title(학교명, dropdown arrow)영역을 누를 경우, 툴팁이 사라지고 다시 나타나지 않습니다.
- 툴팁이 떠있을 때, 해당 영역 바깥영역을 눌러도 툴팁이 포커스를 가져가지 않도록 하였습니다.
- 툴팁이 떠있을 때, 해당 영역 바깥을 눌러도 툴팁이 사라지지 않도록 하였습니다. 
---
TODO)
- 학교/축제 내에 툴팁을 추가하여 위와 같은 동작을 지원하도록 구현
> [feat] 온보딩 완료(툴팁 체크) 여부 DataStore 환경 구축 및 연동 

- feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
- feature/booth/src/main/kotlin/com/unifest/android/feature/booth/navigation/BoothNavigation.kt
- feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
BoothDetail 화면 내에서는 MainScreen의 Scaffold 내에 SnackBar 를 사용하는 것이 아닌, BoothDetail 내에 Snackbar 를 사용하는 것으로 문제 해결 
- 해당 화면에서만 특수하게 bottomPadding 을 필요로 하기 때문 
- Scaffold 를 사용하지 않아도 Snackbar 사용 가능합니다
- 다른 화면들의 경우 MainScreen 의 Scaffold 내에 Snackbar 사용
BoothDetail 화면 내 디자인 디테일 보완
- 글자 하단 정렬시 alignByBaseline() 을 통해 같은 라인에 정렬되도록
- 글씨 폰트 설정, clickable 이벤트 영역 수정
- bottom bar elevation 설정 
- 누락된 컴포넌트 추가  
- [Snackbar 지속시간이 너무 긴거 같아서 조금 줄였습니다](https://velog.io/@mraz3068/Android-Compose-Snackbar-Duration-Custom)
> [fix] [#79] Snackbar 위치 문제 해결 및 Booth 상세 화면 디자인 디테일 보완 

- core/datastore/src/main/kotlin/com/unifest/android/core/datastore/OnboardingDataSourceImpl.kt
- core/datastore/src/main/kotlin/com/unifest/android/core/datastore/RecentLikedFestivalDataSource.kt
- core/datastore/src/main/kotlin/com/unifest/android/core/datastore/RecentLikedFestivalDataSourceImpl.kt
- core/datastore/src/main/kotlin/com/unifest/android/core/datastore/di/DataStoreModule.kt
- core/datastore/src/main/kotlin/com/unifest/android/core/datastore/di/DataStoreQualifier.kt
관심 축제가 여러개 있을 경우 그 중에 가장 마지막에 확인한 관심 축제를 화면에 출력하기 위한 DataStore 환경을 구성하였습니다. 
API 를 통해 잘 동작하나 확인까지 해보려했는데 현재 API 에 문제가 있는 것 같아 확인은 못해봤습니다.
> [feat] [#75] 최근에 확인한 관심 축제를 저장하기 위한 DataStore 환경 구축

- core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/SearchTextField.kt
- core/designsystem/src/main/res/values/strings.xml
- feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
- 아이템 영역을 Swipe 하여도 다음 탭으로 넘어갈 수 있도록 구현
- AllFestivalsTabView -> AllFestivalsTabRow 로 네이밍 변경
- 아이콘 색상 원래 색상에 맞게 보여지도록 수정
- LazyVerticalGrid item 에 대한 key 부여 
- 선택된 Tab 에 대해 글씨의 두께와 색상이 바뀔때, 자연스럽도록 애니메이션 적용
P.S) TabLayout 에 각각의 탭의 Width 를 동적으로 설정하려면 자체 커스텀이 필요할것같습니다. 근데 지금도 전 나쁘지않다고 생각합니다. 
찾아보니 이런 레퍼런스는 있더군요. 정 안되면 참고해서 구현해볼만 한 것 같슴다.
https://medium.com/@gautier.louis/tab-row-made-easy-in-jetpack-compose-8eaa5a602744
> [feat] Intro 화면 ScrollableTapRow, HorizontalPager 연동 

- core/data/src/main/kotlin/com/unifest/android/core/data/repository/OnboardingRepository.kt
- core/data/src/main/kotlin/com/unifest/android/core/data/repository/OnboardingRepositoryImpl.kt
- core/datastore/src/main/kotlin/com/unifest/android/core/datastore/OnboardingDataSource.kt
- core/datastore/src/main/kotlin/com/unifest/android/core/datastore/OnboardingDataSourceImpl.kt
- core/designsystem/build.gradle.kts
- core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/LoadingWheel.kt
- core/designsystem/src/main/res/values/splash.xml
- feature/intro/src/main/AndroidManifest.xml
- feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroActivity.kt
- feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
- feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroUiState.kt
- feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
- Intro dataStore 환경 구축
- SplashScreen API 연동
- Intro 화면 내에 LoadingWheel 적용 및 색상 변경 
- 관심 축제 추가에 따른 추가완료 버튼 활성화 여부 구현
> [feat] [#101] Intro 화면 관심 학교 추가 이후 다시 앱을 켰을 때, 진입되지 않도록 구현  

- core/common/src/main/kotlin/com/unifest/android/core/common/utils/DateUtils.kt
- core/data/src/main/kotlin/com/unifest/android/core/data/mapper/FestivalEntityMapper.kt
- core/data/src/main/kotlin/com/unifest/android/core/data/mapper/FestivalMapper.kt
- core/database/src/main/kotlin/com/unifest/android/core/database/entity/LikedFestivalEntity.kt
- core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/NetworkImage.kt
- core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/StarImage.kt
- core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/theme/Font.kt
- core/model/src/main/kotlin/com/unifest/android/core/model/FestivalTodayModel.kt
- core/network/src/main/kotlin/com/unifest/android/core/network/response/FestivalResponse.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiAction.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiState.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
1. 축제가 있는 날짜에는 청록점이 표시되게 함
2. 축제가 있는 날에는 몇일차인지 계산해서 보이게함(현재는 api가 연결되지 않아 Day 19 이런식으로 보이는데, api를 연결하면 해당날짜에 존재하는 축제만 보일것이므로 문제 없음
3. 연예인 사진 클릭시 어떤 연예인인지 이름 보임 -> 현재는 StarInfoModel에 id가 없어 인덱스 기반으로 상태관리를 작성했는데 같은 name,imgUrl을 사용해서 동시에 이름이 보이고, 사진이 보이는 형태-> 백엔드와 협의해 축제별로 연예인 등록할때 id도 함께 저장하고 내려주게 해볼까 생각중입니다. 아니면 festival Id 별로 또 묶어서 하면되긴하는데 요렇게 해보려다 좀 어려워서 일단은 여기까지 하고 생각을 여쭤보려구요
> [feat] [#104] 홈 화면 기능 구현

- feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/model/BoothDetailMapModel.kt
- gradle/libs.versions.toml
- settings.gradle.kts
이제 네이버 맵에서 자체적으로 Clustering 을 지원하는 관계로 migration 하였습니다.
제가 관련해서 naver-map-compose 깃허브에 [이슈](https://github.com/fornewid/naver-map-compose/issues/101)를 남겼는데, 성용님께서 바로 배포를 해주셔서 1.5.7버전으로 버전 업데이트후 적용하였습니다.
하지만 아직 어떤 문제가 생길지 모르기 때문에 TedClustering 관련한 의존성과 코드는 제거하지 않고, 주석처리만 해두겠습니다.
> [refactor] [#113] Clustering Library Migration

- core/common/src/main/kotlin/com/unifest/android/core/common/FestivalUiAction.kt
- core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalBottomSheet.kt
- core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedFestivalGrid.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/navigation/HomeNavigation.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiEvent.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiState.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
- feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroUiState.kt
- feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
- feature/main/src/main/kotlin/com/unifest/android/feature/main/MainNavController.kt
- feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiState.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
- feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
- feature/menu/src/main/kotlin/com/unifest/android/feature/menu/navigation/MenuNavigation.kt
- feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiEvent.kt
- feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuUiState.kt
- feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
MutableList 또는 List 가 컴포저블 함수의 파라미터로 존재할 경우, 해당 컴포저블 함수는 Stable 판정을 받지 못하여, Unstable 하게 됩니다.
그렇게 되면, 변경 사항이 없어도 recomposition 을 skip 하지 못하고, 매번 recomposition이 수행됩니다. (성능 저하의 원인)
- 따라서 변경 가능성이 있늠 목록을 관리하는 자료구조인 MutableList 를 사용하는 곳들(UiState)의 
파라미터를 persistentList 로 타입을 변경하였습니다. 
- 컴포저블 함수 내에 state 를 제거하여, stateless 하게 변경해주었습니다.
그외)
축제 바텀시트 내에 관심 축제 아이템을 클릭했을 경우에 대한 클릭 이벤트를 구현해주었습니다.
(최근 선택된 관심 축제 변경 -> 바텀시트 닫기 -> 맵화면으로 이동 -> 맵 화면에서는 최근 선택된 관심 축제를 구독하여, 최신 변경 사항을 반영해야함(todo))
> [Refactor] [#114] MutableList -> PersistentList 로 변경

- core/data/src/main/kotlin/com/unifest/android/core/data/repository/BoothRepository.kt
- core/data/src/main/kotlin/com/unifest/android/core/data/repository/BoothRepositoryImpl.kt
- core/network/src/main/kotlin/com/unifest/android/core/network/request/LikeBoothRequest.kt
- core/network/src/main/kotlin/com/unifest/android/core/network/response/LikeBoothResponse.kt
- core/network/src/main/kotlin/com/unifest/android/core/network/service/UnifestService.kt
- feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
UUID 같은 경우는 앱을 삭제하고 생성할때마다 새롭게 갱신이 되는 문제가 있어, 고유 ID 로는 DeviceID 를 사용하였습니다.
실제 구현은 API 문제가 해결되고 하도록 하겠습니다.
> [feat] [#38] 부스 좋아요 API 연동

- core/data/src/main/kotlin/com/unifest/android/core/data/mapper/FestivalMapper.kt
- core/model/src/main/kotlin/com/unifest/android/core/model/FestivalTodayModel.kt
- core/network/src/main/kotlin/com/unifest/android/core/network/response/FestivalResponse.kt
- feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiAction.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiState.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
- 축제 일정 내에 연예인 아이템을 선택했을 때, 같은 List 내에 같은 Index 가 모두 선택되는 것이 아니라, 해당 아이템만 선택되도록 구현했습니다.
- 축제 Title 최대 길이를 fix 시켜, 연예인 목록 리스트가 Row 내에서 항상 같은 지점부터 시작하도록 하였습니다. 
그외)
- 홈 화면 코드 개선(커밋 메세지 참고)
- 오늘의 축제 일정 API 변경 사항 반영
> [feat] [#123] [#121] 홈 화면 이슈 해결  및 코드 개선 

- core/data/src/main/kotlin/com/unifest/android/core/data/mapper/BoothMapper.kt
- core/data/src/main/kotlin/com/unifest/android/core/data/repository/BoothRepositoryImpl.kt
- core/data/src/main/kotlin/com/unifest/android/core/data/repository/LikedBoothRepository.kt
- core/data/src/main/kotlin/com/unifest/android/core/data/repository/LikedBoothRepositoryImpl.kt
- core/database/src/main/kotlin/com/unifest/android/core/database/LikedBoothDao.kt
- core/designsystem/src/main/res/values/strings.xml
- core/network/src/main/kotlin/com/unifest/android/core/network/response/BoothResponse.kt
- core/ui/src/main/kotlin/com/unifest/android/core/ui/component/LikedBoothItem.kt
- feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
- feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothLocationScreen.kt
- feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothUiState.kt
- feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
- feature/liked-booth/src/main/kotlin/com/unifest/android/feature/liked_booth/viewmodel/LikedBoothViewModel.kt
- feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/navigation/MapNavigation.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapUiEvent.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
- feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
feat)
- 부스 좋아요 API 연동
- 축제 내 인기 부스 API 변경 사항 반영
- 부스 위치 화면 네이버 맵 세팅 설정
- 메뉴, 관심 부스 화면 좋아요 취소 API 연동
- 맵 화면 인기 부스 갱신 기능 구현(좋아요를 누르고 돌아왔을 때, 인기 부스 랭킹 갱신을 위함)
- 부스 화면 메뉴가 없는 경우에 대한 케이스 처리(등록된 메뉴가 없어요)
- 상세 조회한 부스가 내가 이미 좋아요를 누른 부스 일 경우, 북마크가 체크되도록 구현
fix)
- 메뉴 화면 LikedBoothItem 잘못 매핑된 정보 수정(category -> warning)
> [feat] 부스 좋아요 API 연동 및 파생되는 기능 구현 

- feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
건국대학교만 현재 서비스함에 따라 다른 학교를 비활성화 했는데, 관심축제에 건대가 포함되지 않을시 부스정보를 가져오지 못하던 파생되는 문제를 수정
> [fix] 관심축제에 건대가 없을시 부스 데이터를 받아오지 못하던 버그 수정

- feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothLocationScreen.kt
- feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroUiState.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
1. 157번 이슈는 패딩을 추가하면서 발생한 문제로, 흰 사각형이 항상 보여 어색하던 이슈였습니다. 패딩을 지우고 대신 카메라 위치를 조정해 수정해주었습니다
2. 158번 이슈는 인트로 화면에서 처음으로 진입했을시에는 selectedRegion이 값이 지정되어있지 않아 ""로 지정되어져 아무 축제값도 보여주지못하는 이슈였습니다. UiState에서 기본값으로 전체를 설정해줘 해결했습니다. (다른 지역검색시 selectedRegion이 새로 지정되므로 문제가 발생하지않음)
3. 159번 이슈는 맵 탑앱바에서의 부스 SearchTextField에서 clearText가 작동하지 않았는데, `it.copy(festivalSearchText = TextFieldValue())` 로 작성되어있던 이슈였습니다. 수정했습니다
4. 160번 이슈는 양옆에 horizontal 패딩을 4dp씩 주어 해결했습니다. 이전 화면인 부스 디테일화면의 앱바에서의 뒤로가기 위치가 같았다면 다른식으로 해결했을텐데 그렇진 않아서 쉽게 해결해뒀습니다. 추가로 부스 상세 위치를 보여주는 지도의 카메라 줌을 수정해주었습니다.
> [fix] [#157] [#158] [#159] [#160] minor bugs fix

- .github/workflows/android-ci.yml
- app/build.gradle.kts
- feature/booth/build.gradle.kts
- feature/home/build.gradle.kts
- feature/intro/build.gradle.kts
- feature/intro/proguard-rules.pro
- feature/liked-booth/build.gradle.kts
- feature/main/build.gradle.kts
- feature/map/build.gradle.kts
- feature/menu/build.gradle.kts
- feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
- feature/waiting/build.gradle.kts
- 운영자 모드 진입 로직 수정 ->  m.naver.com 임시 
- SigningConfig 추가,proguard 추가 
-> release 로 빌드시 아직 하단의 에러 발생 중 
```
FATAL EXCEPTION: main
Process: com.unifest.android, PID: 23793
qb.i: Function 'onAction' (JVM signature: onAction(Lcom/unifest/android/feature/intro/viewmodel/IntroUiAction;)V) not resolved in class ra.r: no members found
... 
```
해당 에러 발생중
> [feat] release setup

- build-logic/src/main/kotlin/com/unifest/android/Config.kt
- core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/AutoResizedText.kt
- core/ui/src/main/kotlin/com/unifest/android/core/ui/component/StarImage.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
- feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroScreen.kt
1. 연예인 이름이 2줄이 되면 중앙정렬이 안되는 문제를 수정하고, 글자크기를 조절해 한줄로 표현되도록 변경
2. 인트로 화면에서 버튼이 학교를 가리는 문제 해결
3. 캘린더에 리플이 어색하던 문제를 해결
> [fix] QA 내역 반영

- core/data/src/main/kotlin/com/unifest/android/core/data/mapper/BoothMapper.kt
- core/network/src/main/kotlin/com/unifest/android/core/network/response/BoothResponse.kt
- core/ui/src/main/kotlin/com/unifest/android/core/ui/component/FestivalBottomSheet.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/HomeScreen.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeUiState.kt
- feature/home/src/main/kotlin/com/unifest/android/feature/home/viewmodel/HomeViewModel.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
- feature/menu/src/main/kotlin/com/unifest/android/feature/menu/MenuScreen.kt
1. Day 값 표현 로직을 변경하여, 사용자가 날짜를 바꾼후 해당날짜의 축제정보를 서버에서 받은후 Day값을 비교하게해 Day -9등으로 보이던 문제를 수정했습니다
2. 부스 디테일과 메뉴에 필수값이 아닌 항목들에 Null처리를 해줬습니다. 이전에는 해당부분이 빠져있어 부스 전체의 정보를 제대로 표시하지 못하는 문제가 있었습니다(예, 플레이쿠라운드 부스의 메뉴사진이 없자 부스상세정보를 전부 표시하지 못함)
3. 바텀시트의 툴팁을 제거하고 간격을 좁혔는데, 이부분은 일단 작성만 해뒀습니다.
> [fix] qa 2차

- build-logic/src/main/kotlin/com/unifest/android/Config.kt
- gradle/libs.versions.toml
앱 버전 관련 config 변수들 libs.versions.toml 로 이동되었습니다
해당 [PR](https://github.com/Project-Unifest/unifest-android/pull/176) 에서 변경된 사항이구요
이유는 앱에 전역에서 버전 정보를 가져올 수 있게 하기 위함입니다.
> [chore] build-logic config 앱 버전 관련 변수 제거

- feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
- feature/booth/src/main/kotlin/com/unifest/android/feature/booth/viewmodel/BoothViewModel.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/PermissionDialog.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
- gradle/libs.versions.toml
feat)
- 위치 권한 요청 부활
- 위치 권한 요청이 허락될 경우 ~~LocationTrackingMode.Follow~~ (지도에 내 위치, 이동 방향이 보이며, 실시간으로 위치가 갱신) 활성화
- NoFollow 로 설정 (Follow 로 하게 될 경우, 지도 자체가 내 위치로 이동함, 내 위치는 추적하되 지도는 이동하지 않는 모드로 변경)
style)
- 부스 상세 화면 진입시 로딩 화면 추가 
- MVP 구현해야할 부분은 다 구현된 것 같고, 눈에 보이는 버그가 당장은 보이지 않아, app version 은 정식 버전인 1.0.0 버전으로 올렸습니다.
> [fix] 위치 권한 요청이 맵 화면 진입시 화면에 출력되지 않는 문제 해결 

- core/designsystem/src/main/res/values/strings.xml
- feature/main/src/main/kotlin/com/unifest/android/feature/main/MainScreen.kt
- gradle/libs.versions.toml
fix)
바텀 네비게이션 중복 클릭 방지 
style)
메뉴 화면 나의 관심 학교 -> 나의 관심 축제로 네이밍 변경 
P.S
연예인 정보를 롱 클릭하였을때, 확대해서 볼 수 있는 기능을 추가하고 싶은데 서버에 저장된 사진 규격이 문제네요..
사진 거 뭐 많아봤자 50개도 안되는데 작업하면 좋을것같은데, 아니면 제가 직접해두 되구,, 아쉬운 부분입니다
> [fix] QA 3차 

- feature/booth/src/main/kotlin/com/unifest/android/feature/booth/BoothDetailScreen.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/MapScreen.kt
- gradle/libs.versions.toml
Map 화면)
- HorizontalPager 내에 아이템의 Location Text 의 길이 제한을 1줄로 하여, 글자 길이에 따른 아이템의 높이가 변화되지 않고, 고정되도록 수정
부스 상세 화면)
- 부스 제목이 화면 전체 가로길이의 2/3 가 넘지않도록 길이 제한
- fontStyle 이 적용되지 않은 Text fontStyle 적용
> [style] 앱 내에 텍스트 길이 제한 및 최대 줄 수 조정

- core/designsystem/src/main/res/drawable/ic_calender_left.xml
- core/designsystem/src/main/res/drawable/ic_calender_right.xml
- feature/home/src/main/kotlin/com/unifest/android/feature/home/Calendar.kt
- gradle/libs.versions.toml
> [design] 축제 개수별 색 변경

- core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/SearchTextField.kt
- core/designsystem/src/main/kotlin/com/unifest/android/core/designsystem/component/Tooltip.kt
- gradle/libs.versions.toml
fix)
TextField
singleLine 적용, Textfield 텍스트 maxLength 제한(20자) 
-> 텍스트가 길어지면 clear icon 을 밀어 텍스트 필드 바깥으로 텍스트가 빠져나가는 문제 해결
ToolTip
Balloon ToolTip 이 좌우, 상하 반전되는 문제를 해결(`setArrowOrientationRules(ArrowOrientationRules.ALIGN_FIXED)`)
해당 옵션을 적용하면, 공간이 협소해도 기존 ArrowOrientation(말풍선 꼬리 위치) 이 유지됩니다. default 옵션인 ALIGN_ANCHORED 로 설정이 되어 있어서, 기존의 ToolTip 에서 발생했던 문제가 발생한 것이었습니다... 문서를 꼼꼼히 읽어봤어야 했는데...(개인적으론 fixed 가 default 면 좋을 것 같긴합니다.)
https://github.com/skydoves/Balloon/issues/692
Balloon 렌더링 지연 시간 적용
Api 호출을 통해 학교명을 가져오는데, 해당 data 가 아직 들어오지 않았을 때("" 빈값) 바로 옆에 툴팁이 렌더링되고, 학교명 데이터를 받아온 후, 이미 렌더링된 툴팁에 의해 학교명이 가려지는 문제 발생하였는데. 500ms 딜레이 부여하여 렌더링 되게 하여, 학교명이 툴팁에 의해 가려지는 문제를 해결하였습니다.
> [fix] ToolTip 및 TextField 관련 이슈 해결 

- core/ui/src/main/kotlin/com/unifest/android/core/ui/component/WaitingDialog.kt
- feature/festival/src/main/kotlin/com/unifest/android/feature/festival/FestivalBottomSheet.kt
style)
웨이팅 다이얼로그)
텍스트의 높이를 제한하여, 핀번호 입력 에러 문구 짤리는 문제 해결 -> 다이얼로그 크기가 늘어나도, 문구가 2줄이 넘어갈때 잘리지 않는게 더 중요
개인정보처리방침 문구 의도치 않게 개행되는 이슈 해결
Before)
After)
FlowRow 를 도입하여 공간이 부족할 경우 다음줄로 개행되도록 수정하였습니다.
축제 바텀시트)
바텀시트 뒤에 영역이 보이도록, 드래그 핸들을 잡고 내릴시 바텀시트가 내려가도록 롤백
> [style] 업데이트 전 UI 관련 디테일 수정 

- feature/festival/src/main/kotlin/com/unifest/android/feature/festival/viewmodel/FestivalViewModel.kt
- feature/intro/src/main/kotlin/com/unifest/android/feature/intro/viewmodel/IntroViewModel.kt
- feature/map/src/main/kotlin/com/unifest/android/feature/map/viewmodel/MapViewModel.kt
- feature/menu/src/main/kotlin/com/unifest/android/feature/menu/viewmodel/MenuViewModel.kt
- feature/splash/src/main/kotlin/com/unifest/android/feature/splash/viewmodel/SplashViewModel.kt
- feature/stamp/src/main/res/values/strings.xml
fix)
- 앱 시작시 로컬 디비에서 최근에 관심 축제로 추가한 학교를 가져와 API 를 호출하는 것이 아닌, 고정된 문자열을 통해 호출
- 관심 축제에서 삭제했을 경우 API 호출시 발생하는 문제를 방지
QA 를 통해 발견된 문제들이 해결되었는지 확인 후 approve - merge 하도록 하겠습니다.(이 브랜치에 미처 발견하지 못한 버그들에 대한 이슈 해결 커밋도 추가하면 될 것 같아요)
> [fix] QA: 학교명을 통한 API 호출 로직 수정

- core/common/src/main/kotlin/com/unifest/android/core/common/HandleQRException.kt
- feature/intro/src/main/kotlin/com/unifest/android/feature/intro/IntroActivity.kt
- feature/stamp/src/main/kotlin/com/unifest/android/feature/stamp/viewmodel/QRScanViewModel.kt
- gradle/libs.versions.toml
이슈)
QRScan 결과로 얻어지는 entryCode 가 boothId 의 타입인 Long 타입 의외에 다른 타입이 얻어지는 경우(ex String, Link 등을 스캔하는 경우)
NumberFormatException 이 발생하여, 앱의 크래시가 발생하는 문제 발생
위의 문제를 해결하였습니다.
> [fix] #287 QRScan NumberFormatException 대응

- build.gradle.kts
- core/data/src/main/kotlin/com/unifest/android/core/data/repository/MessagingRepository.kt
- core/data/src/main/kotlin/com/unifest/android/core/data/repository/MessagingRepositoryImpl.kt
- core/network/src/main/kotlin/com/unifest/android/core/network/request/RegisterFCMTokenRequest.kt
- core/network/src/main/kotlin/com/unifest/android/core/network/response/FCMTokenResponse.kt
- core/network/src/main/kotlin/com/unifest/android/core/network/service/UnifestService.kt
- feature/splash/src/main/kotlin/com/unifest/android/feature/splash/SplashScreen.kt
- feature/splash/src/main/kotlin/com/unifest/android/feature/splash/viewmodel/SplashViewModel.kt
feat)
- FCM Token 등록 API 연동 
refactor)
- 앱 진입시 실행되는 함수 책임 분리 
비고)
앱 진입시 WIFI 또는 데이터 연결이 되어있지 않은 경우, FCM 토큰 발급 및 서버로의 등록이 실패하여 앱내에 FCM 토큰을 사용하는 다른 API 의 동작에서도 문제가 생길 수 있으므로, 해당 플로우로의 진입을 막을 장치가 필요할 것으로 보입니다.(팝업을 띄우고 종료, 스낵바를 띄우고 종료)
해당 기획 및 UI 가 추가 되면 따로 브랜치 파서 작업하도록 하겠습니다.
> [feat] FCM 토큰 등록 api 연동 
